version: '3'

services:
  mongo:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"

  elasticsearch:
    image: bitnami/elasticsearch:latest
    ports:
      - '9200:9200'
      - '9300:9300'

  server:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: "claroforma-server"
    command: npm start
    environment:
        - ENV_NAME=.env.docker
#    volumes:
#      - .:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - mongo
      - elasticsearch
